### ISSUE TITLE
Move IL-DCP code to the connector

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-plugin-mini-accounts#14]
IIUC plugins should treat the data passed to `plugin.sendData` as opaque?

Then this code: https://github.com/interledgerjs/ilp-plugin-mini-accounts/blob/master/index.js#L196 should probably be moved to the connector.

**Comment by sharafian** [comment]
In order to implement the multi-account functionality, plugin mini accounts (and similar multi-plugins) behaves as a very minimal connector. Basically it looks like:

```
client --LPI--> plugin-btp ---\
                               \--BTP->
client --LPI--> plugin-btp -------BTP->  ilp-plugin-mini-accounts  ---LPI---> ilp-connector
                               /--BTP->
client --LPI--> plugin-btp ---/
```

So it's as though mini-accounts is peered with the connector just by being in the same process. The clients aren't connecting to the ilp-connector directly, their upstream is the mini-accounts instance.

**Comment by michielbdejong** [comment]
Right, that makes sense then.
